[project]
name = "alarm-clock"
version = "0.1.0"
#description = "Add your description here"
#readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adafruit-circuitpython-charlcd>=3.5.5",
    "rpi-gpio>=0.7.1",
]
